### ISSUE TITLE
Unable to activate fluent-plugin-splunk-hec-1.2.1, because http_parser.rb-0.6.0 conflicts with http_parser.rb (= 0.5.3)

### ISSUE THREAD

**Issue by BrandonTsai** [splunk/fluent-plugin-k8s-metrics-agg#45]
**What happened**:

I tried to build container image from master branch via the docker/build.sh
But it fail to start when I try to run it in the openshift.

/usr/share/rubygems/rubygems/specification.rb:2325:in `raise_if_conflicts': Unable to activate fluent-plugin-splunk-hec-1.2.1, because http_parser.rb-0.6.0 conflicts with http_parser.rb (= 0.5.3) (Gem::ConflictError)
        from /usr/share/rubygems/rubygems/specification.rb:1438:in `activate'
        from /usr/share/rubygems/rubygems.rb:224:in `rescue in try_activate'
        from /usr/share/rubygems/rubygems.rb:217:in `try_activate'
        from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:128:in `rescue in require'
        from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:39:in `require'
        from /usr/share/gems/gems/fluent-plugin-splunk-hec-1.2.1/lib/fluent/plugin/out_splunk_hec.rb:7:in `<top (required)>'
        from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:59:in `require'
        from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:59:in `require'
        from /usr/local/share/gems/gems/fluentd-1.9.3/lib/fluent/registry.rb:102:in `block in search'
        from /usr/local/share/gems/gems/fluentd-1.9.3/lib/fluent/registry.rb:99:in `each'
        from /usr/local/share/gems/gems/fluentd-1.9.3/lib/fluent/registry.rb:99:in `search'
        from /usr/local/share/gems/gems/fluentd-1.9.3/lib/fluent/registry.rb:44:in `lookup'
        from /usr/local/share/gems/gems/fluentd-1.9.3/lib/fluent/plugin.rb:155:in `new_impl'
        from /usr/local/share/gems/gems/fluentd-1.9.3/lib/fluent/plugin.rb:109:in `new_output'
        from /usr/local/share/gems/gems/fluentd-1.9.3/lib/fluent/agent.rb:130:in `add_match'
        from /usr/local/share/gems/gems/fluentd-1.9.3/lib/fluent/agent.rb:74:in `block in configure'
        from /usr/local/share/gems/gems/fluentd-1.9.3/lib/fluent/agent.rb:64:in `each'
        from /usr/local/share/gems/gems/fluentd-1.9.3/lib/fluent/agent.rb:64:in `configure'
        from /usr/local/share/gems/gems/fluentd-1.9.3/lib/fluent/root_agent.rb:146:in `configure'
        from /usr/local/share/gems/gems/fluentd-1.9.3/lib/fluent/engine.rb:105:in `configure'
        from /usr/local/share/gems/gems/fluentd-1.9.3/lib/fluent/engine.rb:80:in `run_configure'
        from /usr/local/share/gems/gems/fluentd-1.9.3/lib/fluent/supervisor.rb:547:in `run_supervisor'
        from /usr/local/share/gems/gems/fluentd-1.9.3/lib/fluent/command/fluentd.rb:330:in `<top (required)>'
        from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:59:in `require'
        from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:59:in `require'
        from /usr/local/share/gems/gems/fluentd-1.9.3/bin/fluentd:8:in `<top (required)>'
        from /usr/local/bin/fluentd:23:in `load'
        from /usr/local/bin/fluentd:23:in `<main>'

**What you expected to happen**:

CrashLoopBackOff

**How to reproduce it (as minimally and precisely as possible)**:

git clone https://github.com/splunk/fluent-plugin-k8s-metrics-agg.git
cd fluent-plugin-k8s-metrics-agg
./docker/build.sh

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):

Client Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.0+d4cacc0", GitCommit:"d4cacc0", GitTreeState:"clean", BuildDate:"2019-12-24T05:49:02Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.0+d4cacc0", GitCommit:"d4cacc0", GitTreeState:"clean", BuildDate:"2019-12-24T05:49:02Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}

- Ruby version (use `ruby --version`):
ruby 2.5.5p157 (2019-03-15 revision 67260) [x86_64-linux]

- OS (e.g: `cat /etc/os-release`):
NAME="Red Hat Enterprise Linux Server"
VERSION="7.8 (Maipo)"
ID="rhel"
ID_LIKE="fedora"
VARIANT="Server"
VARIANT_ID="server"
VERSION_ID="7.8"
PRETTY_NAME="Red Hat Enterprise Linux Server 7.8 (Maipo)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:7.8:GA:server"
HOME_URL="https://www.redhat.com/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 7"
REDHAT_BUGZILLA_PRODUCT_VERSION=7.8
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="7.8"

- Splunk version:
Splunk Enterprise
Version:
7.2.3

- Others:

**Comment by harshit-splunk** [comment]
Hey @BrandonTsai, I would suggest using `make docker` instead of using  `./docker/build.sh`
We used to use build script for CI pipeline only.

**Comment by harshit-splunk** [comment]
Closing the issue. Feel free to reopen or create new issue if facing the same issue.
